name: recsys
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=22.2.2
  - numpy=1.18.1
  - bottleneck=1.3.5
  - pandas=0.25.1
  - scikit-learn=0.23.1
  - pyyaml=5.1.2
  - protobuf=3.20.3
  - optuna=3.2.0
 
  - pip:
    - tensorflow==1.15.2



