#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gpus=1
#SBATCH --partition=fat_soil_shared
#SBATCH --time=10:00:00
#SBATCH --mem=128GB
#SBATCH --output=tune.out
#SBATCH --error=tune.err

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/recsys/src
source activate recsys

srun python tune.py -m dumf dubpr -d coat yahoo --run_sims 10 -p original bb-item bb-item-user